store:
  db:
    host: 192.168.142.101 # 修改为你自己的虚拟机IP地址
    pw: 123 # 修改为docker中的MySQL密码
    un: root
    database: sg_security
    swagger:
      package: com.store.itemserver.controller
  redis:
    host: localhost
    port: 6379
